name: Build
on:
  push:
    branches-ignore:  [ "1.19" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload jar to artifacts
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar